In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[9.6429e-39, 8.4490e-39, 9.6429e-39],
        [9.2755e-39, 1.0286e-38, 9.0919e-39],
        [8.9082e-39, 9.2755e-39, 8.4490e-39],
        [1.0194e-38, 9.0919e-39, 8.4490e-39],
        [1.0745e-38, 1.0561e-38, 1.0469e-38]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9008, 0.1824, 0.0845],
        [0.0585, 0.1381, 0.5327],
        [0.3181, 0.5343, 0.3928],
        [0.8411, 0.6561, 0.5404],
        [0.7695, 0.3545, 0.9728]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.9067, -1.1520, -0.1913],
        [-0.9468,  0.5524,  1.0708],
        [ 1.3005, -1.1115, -0.8847],
        [-0.6517,  1.7773, -0.0042],
        [-0.3425,  0.5445,  1.0642]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x+y)

tensor([[-0.9067, -1.1520, -0.1913],
        [-0.9468,  0.5524,  1.0708],
        [ 1.3005, -1.1115, -0.8847],
        [-0.6517,  1.7773, -0.0042],
        [-0.3425,  0.5445,  1.0642]])
tensor([[0.1116, 0.2480, 0.5896],
        [0.4267, 0.7830, 0.7738],
        [0.3307, 0.8173, 0.2025],
        [0.4572, 0.4457, 0.6828],
        [0.7503, 0.5705, 0.7710]])
tensor([[-0.7951, -0.9040,  0.3982],
        [-0.5201,  1.3354,  1.8446],
        [ 1.6311, -0.2942, -0.6822],
        [-0.1946,  2.2230,  0.6786],
        [ 0.4078,  1.1151,  1.8352]])


In [9]:
print(torch.add(x, y))

tensor([[-0.7951, -0.9040,  0.3982],
        [-0.5201,  1.3354,  1.8446],
        [ 1.6311, -0.2942, -0.6822],
        [-0.1946,  2.2230,  0.6786],
        [ 0.4078,  1.1151,  1.8352]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.7951, -0.9040,  0.3982],
        [-0.5201,  1.3354,  1.8446],
        [ 1.6311, -0.2942, -0.6822],
        [-0.1946,  2.2230,  0.6786],
        [ 0.4078,  1.1151,  1.8352]])


In [11]:
y.add_(x)
print(y)

tensor([[-0.7951, -0.9040,  0.3982],
        [-0.5201,  1.3354,  1.8446],
        [ 1.6311, -0.2942, -0.6822],
        [-0.1946,  2.2230,  0.6786],
        [ 0.4078,  1.1151,  1.8352]])


In [12]:
print(x[:, 1])

tensor([-1.1520,  0.5524, -1.1115,  1.7773,  0.5445])


In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([3.2222])
3.2222232818603516


# NumPy Bridge

## Converting a Torch Tensor to a Numpy array and vice versa is a breeze.

### The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one wll change the other.

## Converting a Torch Tensor to a NumPy Array

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


## Converting NumPy Array to Torch Tensor

### See how changing the np array changed the Torch Tensor automatically

In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)

array([2., 2., 2., 2., 2.])

In [20]:
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [21]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

Cuda is not available in my laptop environment.....TT