# AutoGrad: Automatic Differentiation

- Central knowledge before going on my first neural network

## Tensor
- torch.Tensor: Central class

In [1]:
import torch

In [3]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


y is created by a torch operation
-> it has a grad_fn

In [5]:
print(y.grad_fn)

In [6]:
z=y*y*3
out=z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


- requires_grad default setting: False<br/>
-> Don't forget to set it as True

In [7]:
a = torch.randn(2, 2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)


False
True


## Gradients
- Backprop!!!

In [8]:
out.backward()

### print gradients d(out)/dx

In [10]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


### torch.autograd -> engine for computing "<i>Vector-Jacobian product<i/>"

example

In [12]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x*2
while y.data.norm()< 1000:
    y=y*2
    
print(y)

tensor([1.2954, 0.8992, 0.0257], requires_grad=True)
tensor([1326.4824,  920.8189,   26.2812], grad_fn=<MulBackward0>)


In [13]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


- stop autograd from tracking history on Tensors with<br>
    <t>.requires_grad=True by<br>
- wraping the code block in<br>
    <t>with torch.no_grad():
 

In [14]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


In [15]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
